---
title: Hackers on the Hill
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
event_name: Hackers on the Hill
url: https://hackersonthehill.org
baseurl: 
google_analytics_key: UA-154554887-1
google_maps_javascript_api_key: AIzaSyCTNQaPLcTx2q3YbOIS49HVB6aaqwNTiAI
eventbrite_embed: 
logo: "/siteicon.png"
description: A semi-regular US Capitol tour with irregulars from the security research
  community.
author:
  name: Beau Woods
  email: 
  twitter: beauwoods
social:
  name: Hackers on the Hill
  twitter: HillHackers
  hashtag: HackersOnTheHill
  links:
  - https://hackersonthehill.org
permalink: pretty
plugins:
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
_comments:
  background_image: Image shown behind the content.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  timezone: The timezone the event dates are listed in
